FROM rocker/r-ver:4

RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-gnutls-dev \
    libxml2-dev \
    libudunits2-dev \
    libgdal-dev \
    libfontconfig1-dev \
    libfribidi-dev  \
    libharfbuzz-dev

#RUN R -e "available.packages()" 

#RUN R -e "chooseCRANmirror(ind = 39); install.packages(c('devtools', 'withr'), lib = 'usr/local/lib/R/library')" 

RUN R -e "chooseCRANmirror(ind = 39); install.packages(c('withr', 'devtools', 'optparse'), lib = 'usr/local/lib/R/library'); withr::with_libpaths(new = 'usr/local/lib/R/library/', devtools::install_github('mpc-bioinformatics/CalibraCurve', dependencies = TRUE, force = TRUE))" 

